language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

env:
    # repository pborreli/composer-service
    # PUSHER_APP_ID= PUSHER_KEY= PUSHER_SECRET=
    - secure: "LwnKMDhBUzxPhbDvBzpdHK6NjXPMlS4gR5ulHKLvcMGnYkpTdiLonOeaC3iNvk3GoFmPjscFrl5YWfy/jh5vg5tUHy8FB3oue3j0GgjiVXRWZa/ccJLjySNfLNTVfmzSNkOxEDRLC3CYIIUK/FPumPBF4g72xLfRT3Zux9PAszw="

services: rabbitmq

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq -y --force-yes nginx-light

before_script:
    - ./.travis_before.sh
    - composer selfupdate
    - composer install -n
    - sudo cp ~/.phpenv/versions/$(phpenv version-name)/bin/composer.phar /usr/local/bin/composer
    - php app/console --env=test sonata:notification:start > /dev/null &
    - phantomjs --webdriver=4444 > /dev/null &

script:
    - bin/phpspec r --format=pretty --verbose
    - bin/behat --format=pretty --verbose

after_failure:
    - cat /var/log/nginx/error.log
    - cat travis_log_php